//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FastEngine_Core_TCPSessionServiceBuiltInWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FastEngine.Core.TCPSessionServiceBuiltIn));
		L.RegVar("Connected", get_Connected, null);
		L.RegVar("Disconnected", get_Disconnected, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FastEngine.Core.TCPSessionServiceBuiltIn>.Check = CheckType;
		StackTraits<FastEngine.Core.TCPSessionServiceBuiltIn>.Push = Push;
	}

	static void Push(IntPtr L, FastEngine.Core.TCPSessionServiceBuiltIn arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FastEngine.Core.TCPSessionServiceBuiltIn), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Connected(IntPtr L)
	{
		ToLua.Push(L, FastEngine.Core.TCPSessionServiceBuiltIn.Connected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Disconnected(IntPtr L)
	{
		ToLua.Push(L, FastEngine.Core.TCPSessionServiceBuiltIn.Disconnected);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FastEngine.Core.TCPSessionServiceBuiltIn o = (FastEngine.Core.TCPSessionServiceBuiltIn)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

