//this source code was auto-generated by tolua#, do not modify it
using System;
using UnityEngine;
using LuaInterface;

public static class LuaBinder
{
	public static void Bind(LuaState L)
	{
		float t = Time.realtimeSinceStartup;
		L.BeginModule(null);
		LuaInterface_DebuggerWrap.Register(L);
		L.BeginModule("UnityEngine");
		UnityEngine_GameObjectWrap.Register(L);
		UnityEngine_TransformWrap.Register(L);
		UnityEngine_ComponentWrap.Register(L);
		UnityEngine_BehaviourWrap.Register(L);
		UnityEngine_MonoBehaviourWrap.Register(L);
		UnityEngine_TimeWrap.Register(L);
		UnityEngine_AssetBundleWrap.Register(L);
		L.EndModule();
		L.BeginModule("FairyGUI");
		FairyGUI_EventContextWrap.Register(L);
		FairyGUI_EventDispatcherWrap.Register(L);
		FairyGUI_EventListenerWrap.Register(L);
		FairyGUI_InputEventWrap.Register(L);
		FairyGUI_DisplayObjectWrap.Register(L);
		FairyGUI_ContainerWrap.Register(L);
		FairyGUI_StageWrap.Register(L);
		FairyGUI_ControllerWrap.Register(L);
		FairyGUI_GObjectWrap.Register(L);
		FairyGUI_GGraphWrap.Register(L);
		FairyGUI_GGroupWrap.Register(L);
		FairyGUI_GImageWrap.Register(L);
		FairyGUI_GLoaderWrap.Register(L);
		FairyGUI_GMovieClipWrap.Register(L);
		FairyGUI_TextFormatWrap.Register(L);
		FairyGUI_GTextFieldWrap.Register(L);
		FairyGUI_GRichTextFieldWrap.Register(L);
		FairyGUI_GTextInputWrap.Register(L);
		FairyGUI_GComponentWrap.Register(L);
		FairyGUI_GListWrap.Register(L);
		FairyGUI_GRootWrap.Register(L);
		FairyGUI_GLabelWrap.Register(L);
		FairyGUI_GButtonWrap.Register(L);
		FairyGUI_GComboBoxWrap.Register(L);
		FairyGUI_GProgressBarWrap.Register(L);
		FairyGUI_GSliderWrap.Register(L);
		FairyGUI_ScrollPaneWrap.Register(L);
		FairyGUI_TransitionWrap.Register(L);
		FairyGUI_GObjectPoolWrap.Register(L);
		FairyGUI_RelationsWrap.Register(L);
		FairyGUI_RelationTypeWrap.Register(L);
		FairyGUI_GTweenWrap.Register(L);
		FairyGUI_GTweenerWrap.Register(L);
		FairyGUI_EaseTypeWrap.Register(L);
		FairyGUI_TweenValueWrap.Register(L);
		FairyGUI_UIObjectFactoryWrap.Register(L);
		FairyGUI_UIPackageWrap.Register(L);
		FairyGUI_WindowWrap.Register(L);
		L.RegFunction("EventCallback1", FairyGUI_EventCallback1);
		L.RegFunction("EventCallback0", FairyGUI_EventCallback0);
		L.RegFunction("ListItemRenderer", FairyGUI_ListItemRenderer);
		L.RegFunction("ListItemProvider", FairyGUI_ListItemProvider);
		L.RegFunction("PlayCompleteCallback", FairyGUI_PlayCompleteCallback);
		L.RegFunction("TransitionHook", FairyGUI_TransitionHook);
		L.RegFunction("GTweenCallback", FairyGUI_GTweenCallback);
		L.RegFunction("GTweenCallback1", FairyGUI_GTweenCallback1);
		L.BeginModule("GObjectPool");
		L.RegFunction("InitCallbackDelegate", FairyGUI_GObjectPool_InitCallbackDelegate);
		L.EndModule();
		L.BeginModule("UIObjectFactory");
		L.RegFunction("GComponentCreator", FairyGUI_UIObjectFactory_GComponentCreator);
		L.RegFunction("GLoaderCreator", FairyGUI_UIObjectFactory_GLoaderCreator);
		L.EndModule();
		L.BeginModule("UIPackage");
		L.RegFunction("LoadResource", FairyGUI_UIPackage_LoadResource);
		L.RegFunction("CreateObjectCallback", FairyGUI_UIPackage_CreateObjectCallback);
		L.EndModule();
		L.EndModule();
		L.BeginModule("FastEngine");
		FastEngine_AppWrap.Register(L);
		FastEngine_AppRunModelWrap.Register(L);
		FastEngine_MonoSingleton_FastEngine_AppWrap.Register(L);
		FastEngine_MonoSingleton_FastEngine_Core_TCPSessionWrap.Register(L);
		FastEngine_MonoSingleton_FastEngine_Core_LocalizationWrap.Register(L);
		L.RegFunction("AppBehaviourCallback", FastEngine_AppBehaviourCallback);
		L.BeginModule("Core");
		FastEngine_Core_SocketPackWrap.Register(L);
		FastEngine_Core_TCPSessionWrap.Register(L);
		FastEngine_Core_TCPSessionServiceWrap.Register(L);
		FastEngine_Core_TCPSessionServiceBuiltInWrap.Register(L);
		FastEngine_Core_LocalizationWrap.Register(L);
		L.RegFunction("TCPSessionServiceEventCallabck", FastEngine_Core_TCPSessionServiceEventCallabck);
		L.RegFunction("TCPSessionServiceBuiltInEventCallabck", FastEngine_Core_TCPSessionServiceBuiltInEventCallabck);
		L.EndModule();
		L.BeginModule("FUI");
		FastEngine_FUI_FWindowWrap.Register(L);
		FastEngine_FUI_FLayerWrap.Register(L);
		FastEngine_FUI_FWindowStateWrap.Register(L);
		L.EndModule();
		L.EndModule();
		L.EndModule();
		Debugger.Log("Register lua type cost time: {0}", Time.realtimeSinceStartup - t);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_EventCallback1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.EventCallback1>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.EventCallback1>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_EventCallback0(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.EventCallback0>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.EventCallback0>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_ListItemRenderer(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.ListItemRenderer>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.ListItemRenderer>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_ListItemProvider(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.ListItemProvider>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.ListItemProvider>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_PlayCompleteCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.PlayCompleteCallback>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.PlayCompleteCallback>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_TransitionHook(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.TransitionHook>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.TransitionHook>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_GTweenCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.GTweenCallback>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.GTweenCallback>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_GTweenCallback1(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.GTweenCallback1>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.GTweenCallback1>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_GObjectPool_InitCallbackDelegate(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.GObjectPool.InitCallbackDelegate>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.GObjectPool.InitCallbackDelegate>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIObjectFactory_GComponentCreator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIObjectFactory_GLoaderCreator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIPackage_LoadResource(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIPackage.LoadResource>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIPackage.LoadResource>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FairyGUI_UIPackage_CreateObjectCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FairyGUI.UIPackage.CreateObjectCallback>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FairyGUI.UIPackage.CreateObjectCallback>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FastEngine_AppBehaviourCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FastEngine.AppBehaviourCallback>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FastEngine.AppBehaviourCallback>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FastEngine_Core_TCPSessionServiceEventCallabck(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FastEngine.Core.TCPSessionServiceEventCallabck>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FastEngine.Core.TCPSessionServiceEventCallabck>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FastEngine_Core_TCPSessionServiceBuiltInEventCallabck(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			LuaFunction func = ToLua.CheckLuaFunction(L, 1);

			if (count == 1)
			{
				Delegate arg1 = DelegateTraits<FastEngine.Core.TCPSessionServiceBuiltInEventCallabck>.Create(func);
				ToLua.Push(L, arg1);
			}
			else
			{
				LuaTable self = ToLua.CheckLuaTable(L, 2);
				Delegate arg1 = DelegateTraits<FastEngine.Core.TCPSessionServiceBuiltInEventCallabck>.Create(func, self);
				ToLua.Push(L, arg1);
			}
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

